# -*- coding: utf-8 -*-
"""Apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EqHoLt2JNCWwSrX3xHs4GvXUxKLmcjQm
"""

import mlxtend
import numpy as np
import pandas as pd

data = np.array([['우유', '기저귀', '주스'],
                 ['양상추', '기저귀', '맥주'],
                 ['우유', '양상추', '기저귀', '맥주'],
                 ['양상추', '맥주']
                 ])

from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

# Commented out IPython magic to ensure Python compatibility.
# %%time
# from mlxtend.frequent_patterns import apriori
# 
# ap_df = apriori(df, min_support=0.5, use_colnames=True)

ap_df

